### PR TITLE
More robust url-encoding

### PR DESCRIPTION
**Pull request by jjacobskind**
This PR url-encodes characters that were previously stripped from query parameters. This PR also encodes some url-safe characters that JWPlayer requires to be url-encoded for some reason.

### CODE REVIEW

**Review by IchordeDionysos — APPROVED** [review]
Yeah, sounds great!
I have done something similar when I wrote a JW node implementation

**Comment by IchordeDionysos** [comment]
@pedrettin Can this be merged?

**Comment by IchordeDionysos** [comment]
This pull request would also fix problems with umlauts like ä and ü.

**Comment by pedrettin** [comment]
Yes, this is a good idea. Thanks @jjacobskind for the PR

**Pull request merged**
